test

diff --git a/7.3/Dockerfile b/7.3/Dockerfile
--- a/7.3/Dockerfile
+++ b/7.3/Dockerfile
@@ -116,12 +116,14 @@ ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
 RUN apt-get -y install libfcgi0ldbl nano htop iotop lsof cron mariadb-client redis-tools
 
 # install composer
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
-	&& php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
-	&& php composer-setup.php \
-	&& php -r "unlink('composer-setup.php');" \
-	&& mv composer.phar /usr/local/sbin/composer \
-	&& chmod +x /usr/local/sbin/composer
+RUN EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" && \
+	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+	ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
+	if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then >&2 echo 'ERROR: Invalid installer checksum' && exit 1; fi
+
+RUN php composer-setup.php --quiet && rm composer-setup.php && \
+	mv composer.phar /usr/local/sbin/composer && \
+	chmod +x /usr/local/sbin/composer
 
 # install NewRelic agent
 RUN echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list && \
diff --git a/7.4/Dockerfile b/7.4/Dockerfile
--- a/7.4/Dockerfile
+++ b/7.4/Dockerfile
@@ -120,10 +120,7 @@ RUN apt-get -y install libfcgi0ldbl nano htop iotop lsof cron mariadb-client red
 RUN EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" && \
 	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
 	ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
-	if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
-	>&2 echo 'ERROR: Invalid installer checksum' && rm composer-setup.php \
-	exit 1 \
-	fi
+	if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then >&2 echo 'ERROR: Invalid installer checksum' && exit 1; fi
 
 RUN php composer-setup.php --quiet && rm composer-setup.php && \
 	mv composer.phar /usr/local/sbin/composer && \
