fix for composer install

diff --git a/7.4/Dockerfile b/7.4/Dockerfile
--- a/7.4/Dockerfile
+++ b/7.4/Dockerfile
@@ -117,10 +117,15 @@ ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
 RUN apt-get -y install libfcgi0ldbl nano htop iotop lsof cron mariadb-client redis-tools
 
 # install composer
-RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
-	php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
-	php composer-setup.php && \
-	php -r "unlink('composer-setup.php');" && \
+RUN EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)" && \
+	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
+	ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" && \
+	if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
+	>&2 echo 'ERROR: Invalid installer checksum' && rm composer-setup.php \
+	exit 1 && \
+	fi
+
+RUN php composer-setup.php --quiet && rm composer-setup.php && \
 	mv composer.phar /usr/local/sbin/composer && \
 	chmod +x /usr/local/sbin/composer
 
